stages:
    - build
    - test
build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch "build/test.txt"
        - composer install
        - ./vendor/bin/phpunit phpunit/
    artifacts:
        paths:
            - build/
test:
   stage: test
   script:
       - echo "Testing"
       - test -f "build/test.txt"
