stages:
    - build
    - phpunit
build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch "build/test.txt"
        - composer install
    artifacts:
        paths:
            - ./
test:
   stage: phpunit
   script:
       - echo "PHP Unit"
       - ./vendor/bin/phpunit phpunit/
